#image ekt name ekk dunna
#FROM nginx:latest

#menna mehmi version eka danne tag ekath ekkala 
FROM nginx:1.17.2-alpine


#me file ek athule thiyna okkoma adla image eke vloume ekt damma , hodt mathk thiygnna mehtndi host computer eke volume ekkui container eke volume eki connect kala newei , meke thiyna ewa damma container volume ekt
ADD . /usr/share/nginx/html 